### ISSUE TITLE
Error in database priming

### ISSUE THREAD

**Issue by pradeepdogga** [jonhoo/trawler#2]
Hi there ! I setup MySQL database and loaded schema from lobsters and ran trawler with --prime to load the database with stories and comments.  It seems to be getting an error from lobsters while it is adding stories. Please find the html response from lobsters. I've applied the patch and about 5k users are populated in the database, but each time when stories are being populated it runs into the following error and stops.

![screenshot 1](https://user-images.githubusercontent.com/19299967/50191332-47160280-02e2-11e9-863a-813f7eb4694d.png)
![screenshot 2](https://user-images.githubusercontent.com/19299967/50191333-47ae9900-02e2-11e9-800a-6a9f2809eaa1.png)

Any help is appreciated !

Thanks,
Pradeep.

**Comment by jonhoo** [comment]
Hi Pradeep!

That's interesting.. The error suggests that you may want to increase the connection pool size for the lobste.rs deployment so it can handle more concurrent requests. But barring that you can also just limit the number of concurrent requests `trawler` generates by invoking [`WorkloadBuilder::in_flight`](https://github.com/jonhoo/trawler/blob/9d9ebf2fe2d518340eba332756bc82a9ed28b5e1/src/lib.rs#L115) around [here](https://github.com/jonhoo/trawler/blob/9d9ebf2fe2d518340eba332756bc82a9ed28b5e1/src/bin/main.rs#L346).

Let me know if that fixes anything?
Jon

**Comment by pradeepdogga** [comment]
It worked ! Thanks a lot for the clarification and trawler :) 

Pradeep.
