### ISSUE TITLE
Redirection while priming comments

### ISSUE THREAD

**Issue by pradeepdogga** [jonhoo/trawler#3]
Hi,

While priming users and stories is working fine, trawler is reporting an error after adding the first comment and vote. Please find the screenshot which indicates the error. Can you help me out ?

![screenshot 8](https://user-images.githubusercontent.com/19299967/50427819-69b99580-0865-11e9-8d77-c2507e3dadc7.png)

https://github.com/lobsters/lobsters/blob/11592ac0a6d28e7b935fe6b78e3e5821a45d2af3/app/controllers/comments_controller.rb#L52
      if request.xhr?
Is it due to the above line in lobsters /app/controllers/comments_controller.rb ?

Thanks,
Pradeep.

**Comment by pradeepdogga** [comment]
I've edited the else condition for the line 52 in the file I mentioned to give the same reponse as if it is xmlhttprequest and it worked. But I wonder if you've come across the same issue ?

**Comment by jonhoo** [comment]
Hmm, interesting.. Maybe this is a change they made recently. I think the solution here is to make [this code](https://github.com/jonhoo/trawler/blob/9d9ebf2fe2d518340eba332756bc82a9ed28b5e1/src/bin/main.rs#L253) more liberal. Specifically, make it do
```rust
if res.status().is_success() || res.status().is_redirect()
```
We *could* be stricter and make `hyper` follow the redirect, but that's likely more hassle than it's worth.

The other strategy here would be to use the AJAX API instead. This would require a little bit more engineering, but shouldn't be too bad. You have to change the payload to be JSON (I think), and then set `X-Requested-With` to make [Rails believe it's an xhr request](https://github.com/rails/rails/blob/9ef26accd28e3a53a0e9180b2230806480e6144d/actionpack/lib/action_dispatch/http/request.rb#L266).

**Comment by pradeepdogga** [comment]
I agree with you. It seems like a recent change in lobste.rs
